source 'https://rubygems.org'
gem 'sinatra'
gem 'json'
gem 'sinatra-contrib'
gem 'nokogiri'
gem 'httpclient'
gem 'thin'
gem 'logger'
gem 'couchbase'
gem 'instrumental_agent'
gem 'pirate_metrics_agent'

